# Site settings
site: "blog"
title: "Stephen Cleary"
description: "Stephen Cleary's website: blog, projects, publications, and other computer sciency thingys."
baseurl: ""
url: "http://stephencleary.com"
feed: "http://feeds.feedburner.com/NitoPrograms"
port: 4001

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:title.html
destination: ../../www-gh-pages
