# Site settings
url: "http://localhost:4001"
url_blog: "http://localhost:4000"
url_www: "http://localhost:4001"
port: 4001
feed: "http://localhost:4000/feed.xml"
future: true
local: true
destination: ../build/www-local
