# Site settings
title: "Stephen Cleary"
description: "Stephen Cleary's website: blog, projects, publications, and other computer sciencey things."
baseurl: ""
url: "https://stephencleary.com"
url_blog: "https://blog.stephencleary.com"
url_www: "https://stephencleary.com"
feed: "http://feeds.feedburner.com/NitoPrograms"
highlighter: "pygments"

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:title.html
destination: ../../stephencleary.com-www
exclude: [_posts, assets, feed.xml]
future: false
encoding: UTF-8
