# Site settings
title: "Stephen Cleary (the blog)"
description: "Stephen Cleary's blog: async/await, programming, language design, and other sundry computer science topics."
baseurl: ""
url: "http://blog.stephencleary.com"

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:title.html
