# Site settings
title: "Stephen Cleary (the blog)"
description: "Stephen Cleary's blog: async/await, programming, language design, and other sundry computer science topics."
baseurl: ""
url: "https://blog.stephencleary.com"
url_blog: "https://blog.stephencleary.com"
url_www: "https://stephencleary.com"
feed: "http://feeds.feedburner.com/NitoPrograms"
highlighter: "pygments"

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:title.html
destination: ../build/blog
exclude: [www.assets, book, contact, css, god, icons, projects, publications, search, syndicate, videos, ads.txt, opensearch.xml, _config.blog.local.yml, _config.blog.yml, _config.www.local.yml, _config.www.yml]
future: false
encoding: UTF-8
