# Site settings
title: "Stephen Cleary (the blog)"
description: "Stephen Cleary's blog: async/await, programming, language design, and other sundry computer science topics."
baseurl: ""
url: "http://blog.stephencleary.com"
feed: "/feed.xml"
# feed: "http://feeds.feedburner.com/NitoPrograms"

series:
 -
   name: "Managed Services"
   posts:
    - "Intro"
    - "Basics"
    - "Network Drives"
    - "User Interfaces"

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:title.html
destination: ../../gh-pages