# Site settings
title: "Stephen Cleary"
description: "Stephen Cleary's website: blog, projects, publications, and other computer sciencey things."
baseurl: ""
url: "http://stephencleary.com"
url_blog: "http://blog.stephencleary.com"
url_www: "http://stephencleary.com"
feed: "http://feeds.feedburner.com/NitoPrograms"

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:title.html
destination: ../../www-gh-pages
exclude: [_posts, assets, feed.xml]
future: false
encoding: UTF-8
