# Site settings
title: "Stephen Cleary (the blog)"
description: "Stephen Cleary's blog: async/await, programming, language design, and other sundry computer science topics."
baseurl: ""
url: "http://blog.stephencleary.com"
url_blog: "http://blog.stephencleary.com"
url_www: "http://stephencleary.com"
feed: "http://feeds.feedburner.com/NitoPrograms"

series:
 -
   name: "Managed Services"
   posts:
    - "Intro"
    - "Basics"
    - "Network Drives"
    - "User Interfaces"
 -
   name: "TCP/IP .NET Sockets FAQ"
   posts:
    - "Overview"
    - "Message Framing"
    - "Half-Open Connections"
    - "Application Protocol Specifications"
    - "XML"
    - "Socket Operations"
    - "Error Handling"
    - "Client Sockets"
    - "Server Sockets"
    - "Connected Sockets"
    - "Resources"
    - "The Local IP Address"
    - "Length-Prefix Example"
    - "Local IP Addresses Example"
 -
   name: "IDisposable and Finalizers"
   posts:
    - "Three Rules"
    - "Rule 1: Don't"
    - "Rule 2: Managed Resources"
    - "Rule 3: Unmanaged Resource"
    - "Q&A: When to Call SuppressFinalize?"
    - "Q&A: Is KeepAlive Required in Dispose?"
    - "Q&A: Is KeepAlive Required with SuppressFinalize?"
    - "Q&A: Seting Variables to Null"
    - "Finalizers During Shutdown"

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:title.html
destination: ../../gh-pages
exclude: [contact,projects,publications]




# Site settings
url: "http://localhost:4000"
url_blog: "http://localhost:4000"
url_www: "http://localhost:4001"
feed: "/feed.xml"
